const WIDTH = 288;
const HEIGHT = 512;
const FPS = 60;

const GRAVITY = 1;
const SUSHI_SPEED = 4;
const GAP_SIZE = 150;

const WEAK_JUMP_THRESHOLD = 4;
const STRONG_JUMP_THRESHOLD = 8;
const WEAK_JUMP_STRENGTH = 8;
const MAX_JUMP_STRENGTH = 15;
